@startuml iniciar_juego

class Inicio
class Constantes
class Jugador
class Pantalla
class Tumbas
class Zombies
class pygame
class sys
class Sprite

Inicio <|-- Jugador
Inicio <|-- Constantes
Inicio <|-- Pantalla
Inicio <|-- Tumbas
Inicio <|-- Zombies
Inicio <|-- pygame
Inicio <|-- sys
Inicio <|-- Sprite

class Main {
    +main()
}

Main ..> Inicio

Main ..> Constantes
Main ..> Jugador
Main ..> Pantalla
Main ..> Tumbas
Main ..> Zombies
Main ..> pygame
Main ..> sys
Main ..> Sprite

Main --> Inicio: iniciar_juego
Main --> Pantalla: screen
Main --> Jugador: juanito
Main --> Zombies: zombies
Main --> Tumbas: tumbas
Main --> pygame: pygame.init()
Main --> sys: sys.exit()
Main --> pygame: pygame.display.set_caption("Juan y sus Zombies")
Main --> pygame: background_image = pygame.image.load("../imagenes/fondo.jpg").convert()
Main --> pygame: screen = pygame.display.set_mode(Tamaño_pantalla)
Main --> Jugador: Juan(Tamaño_pantalla)
Main --> Tumbas: []
Main --> Zombies: []
Main --> pygame: pygame.event.get()
Main --> pygame: pygame.display.update()
Main --> pygame: pygame.time.delay(10)
Main --> Jugador: juanito.animar()
Main --> pygame: screen.blit(juanito.imagen, juanito.rect)
Main --> Tumbas: tumPlay(juanito, tumbas, puntos)
Main --> Jugador: juanito.balas.draw(screen)
Main --> Jugador: juanito.espadas.draw(screen)
Main --> pygame: pygame.quit()

@enduml
